//=========================================================
// src/sin_generator_v1.0_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8LB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

char raise = 30,//40,						//raise position for sin_table
		fall = 80;//90;						//fall position for sin table

const unsigned int code N = 100;
const unsigned int code sin_table[100] = {1024,1089,1153,1216,1279,1341,1401,1460,1518,1573,1626,1677,1725,1771,1813,1853,1889,
	1922,1951,1976,1998,2016,2030,2040,2046,2048,2046,2040,2030,2016,1998,1976,1951,1922,
	1889,1853,1813,1771,1725,1677,1626,1573,1518,1460,1401,1341,1279,1216,1153,1089,1024,
	960,896,832,770,708,647,588,531,476,422,372,323,278,235,196,160,127,98,72,50,32,18,8,
	2,0,2,8,18,32,50,72,98,127,160,196,235,278,323,372,422,476,531,588,647,708,770,832,896,960};

sbit SYNC = P1 ^ 1;
//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void) {
	// $[SiLabs Startup]
	// [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main(void) {
	unsigned int i = 0;
	int j = 0;
	static int page_bak;
	char shift;
	volatile unsigned int pp;
	// Call hardware initialization routine
	enter_DefaultMode_from_RESET();

	pp = (P1 & 0x38) >> 3;
	shift = (((P1 & 0x38) >> 3) - 3) * 2;

	raise += shift;
	fall += shift;

	page_bak = SFRPAGE;
	SFRPAGE = 0x30;
	while (1) {

		DAC0L = sin_table[i];
		DAC0H = sin_table[i] >> 8;
		//SFRPAGE = page_bak;

		if (i == raise)
			SYNC = 1;
		if (i == fall)
			SYNC = 0;

		++i;
		if (i == N)
			i = 0;

		/*		NOP();
		 NOP();
		 NOP();
		 NOP();
		 NOP();
		 NOP();
		 NOP();
		 NOP();
		 NOP();
		 NOP();
		 NOP();
		 NOP();*/
// $[Generated Run-time code]
// [Generated Run-time code]$
	}
}
